#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FlowMind Cashflow — Assembly From Audio v1
Builds final.mp4 using master.wav as the master clock.

Video source priority:
  1) assets/cache/<PROJECT_ID>/video/motion_bg.mp4  (generated by video_motion_dummy_v1)
  2) test_video.mp4 (repo root)

Usage:
  python -m engine.assembly_from_audio_v1 FM_TEST
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Tuple


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _read_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _run(cmd: list[str]) -> Tuple[int, str]:
    p = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    return p.returncode, p.stdout


def _require_tools() -> None:
    rc, _ = _run(["ffmpeg", "-version"])
    if rc != 0:
        raise RuntimeError("ffmpeg not found in PATH")
    rc, _ = _run(["ffprobe", "-version"])
    if rc != 0:
        raise RuntimeError("ffprobe not found in PATH")


def _probe_duration_sec(media: Path) -> float:
    cmd = ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "json", str(media)]
    rc, out = _run(cmd)
    if rc != 0:
        raise RuntimeError(f"ffprobe failed rc={rc}\n{out}")
    data = json.loads(out)
    return float(data["format"]["duration"])


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("Usage: python -m engine.assembly_from_audio_v1 <PROJECT_ID>", file=sys.stderr)
        return 2

    project_id = argv[1]
    project_dir = (Path("projects") / project_id).resolve()
    if not project_dir.exists():
        print(f"[FAIL] missing project dir: {project_dir}", file=sys.stderr)
        return 3

    audio_render = project_dir / "AUDIO_RENDER.json"
    if not audio_render.exists():
        print(f"[FAIL] missing AUDIO_RENDER.json: {audio_render}", file=sys.stderr)
        return 4

    ar = _read_json(audio_render)
    master_wav = Path((ar.get("outputs") or {}).get("master_wav") or "").expanduser().resolve()
    if not master_wav.exists():
        print(f"[FAIL] missing master_wav: {master_wav}", file=sys.stderr)
        return 5

    # video source priority
    motion_bg = (Path("assets") / "cache" / project_id / "video" / "motion_bg.mp4").resolve()
    if motion_bg.exists():
        video_src = motion_bg
        video_src_kind = "motion_bg"
    else:
        video_src = Path("test_video.mp4").resolve()
        video_src_kind = "test_video"
        if not video_src.exists():
            print(f"[FAIL] missing test_video.mp4 in repo root: {video_src}", file=sys.stderr)
            return 6

    try:
        _require_tools()
        dur = _probe_duration_sec(master_wav)
    except Exception as e:
        print(f"[FAIL] preflight: {e}", file=sys.stderr)
        return 7

    out_dir = (Path("out") / project_id).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    final_mp4 = out_dir / "final.mp4"
    ffprobe_json = out_dir / "ffprobe.json"

    cmd = [
        "ffmpeg",
        "-y",
        "-stream_loop",
        "-1",
        "-i",
        str(video_src),
        "-i",
        str(master_wav),
        "-t",
        f"{dur:.3f}",
        "-r",
        "30",
        "-vf",
        "scale=1920:1080:force_original_aspect_ratio=decrease,"
        "pad=1920:1080:(ow-iw)/2:(oh-ih)/2,"
        "setsar=1,format=yuv420p",
        "-c:v",
        "libx264",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-ar",
        "48000",
        "-ac",
        "2",
        "-movflags",
        "+faststart",
        str(final_mp4),
    ]
    rc, out = _run(cmd)
    if rc != 0:
        print(f"[FAIL] ffmpeg assembly rc={rc}\n{out}", file=sys.stderr)
        return 8

    cmdp = ["ffprobe", "-v", "error", "-show_streams", "-show_format", "-of", "json", str(final_mp4)]
    rc2, out2 = _run(cmdp)
    if rc2 != 0:
        print(f"[FAIL] ffprobe final rc={rc2}\n{out2}", file=sys.stderr)
        return 9
    ffprobe_json.write_text(out2 + "\n", encoding="utf-8")

    marker = project_dir / "ASSEMBLY_FROM_AUDIO.json"
    marker_data = {
        "project_id": project_id,
        "generated_at": _utc_now_iso(),
        "inputs": {"master_wav": str(master_wav), "video_src": str(video_src), "video_src_kind": video_src_kind},
        "duration_sec": float(dur),
        "outputs": {"final_mp4": str(final_mp4), "ffprobe_json": str(ffprobe_json)},
        "note": "Assembly uses master audio clock. Video loops until audio ends.",
    }
    marker.write_text(json.dumps(marker_data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"[ASSEMBLY_FROM_AUDIO PASS] video_src_kind={video_src_kind} src={video_src}")
    print(f"[ASSEMBLY_FROM_AUDIO PASS] final={final_mp4}")
    print(f"[ASSEMBLY_FROM_AUDIO PASS] ffprobe={ffprobe_json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
